theme = "gruvbox_robert"

[editor]
line-number = "relative"
completion-trigger-len = 1
true-color = true

# [editor.whitespace]
# render = "all"

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "all"

[editor.whitespace.characters]
newline = "↵"

[editor.lsp]
display-messages = true

[editor.cursor-shape]
insert = "bar"

# Copying some Vim/NeoVim mappings to make me a little happier
[keys.normal]
C-r = "redo"
0 = "goto_line_start"
D = ["collapse_selection", "extend_to_line_end", "delete_selection"]
C-f = "file_picker"

[keys.normal.space]
d = ":buffer-close"

# Like an IDE :)
[keys.insert]
C-space = "completion"
