# Changes the cursor and selection colors
theme = "gruvbox_robert"

[editor]
line-number = "relative"
completion-trigger-len = 1
idle-timeout = 0
true-color = true
cursorline = true
color-modes = true

[editor.whitespace.render]
newline = "all"

[editor.whitespace.characters]
newline = "↵"

[editor.lsp]
display-messages = true

[editor.cursor-shape]
insert = "bar"

[editor.indent-guides]
render = true
character = "▏"

[editor.file-picker]
ignore = false
hidden = false

[keys.normal]
# "Select inner line", mirrors x's "select a line"
X = ["goto_first_nonwhitespace", "select_mode", "goto_line_end", "normal_mode"]

[keys.select]
";" = ["collapse_selection", "normal_mode"]

[keys.normal.space]
d = ":buffer-close"

[keys.insert]
C-space = "completion"
