[[language]]
name = "markdown"
file-types = ["md", "markdown", "mdx"]

[[language]]
name = "python"
language-server = { command = "pyright-langserver", args = ["--stdio"] }
auto-format = true
config = ""